#!/bin/bash
#=============================================================================
# Fang Research OS v1.0 - PhD Deep Analysis Script
# 博士深度分析腳本
# 
# 用法:
#   bash scripts/phd_deep_analysis.sh --input <FILE> [--output <DIR>] [--model <MODEL>]
#
# 示例:
#   bash scripts/phd_deep_analysis.sh --input data/papers/sample.md
#   bash scripts/phd_deep_analysis.sh --input data/papers/sample.md --output outputs/
#   bash scripts/phd_deep_analysis.sh --input "IAQ and mmWave" --mode topic
#=============================================================================

set -euo pipefail

# 顏色定義
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 配置
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$ROOT_DIR/config/f-ros.yaml"

# 預設值
INPUT=""
OUTPUT_DIR="$ROOT_DIR/outputs"
MODEL="deepseek-v3"
MODE="file"
VERBOSE=false
HELP=false

#----------------------------------------------------------------------------
# 函數定義
#----------------------------------------------------------------------------

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

show_help() {
    cat << EOF
Fang Research OS v1.0 - PhD Deep Analysis Script

用法:
    bash $0 [OPTIONS]

選項:
    --input, -i <FILE/TOPIC>    輸入檔案或研究主題 (必填)
    --output, -o <DIR>          輸出目錄 (預設: ./outputs)
    --model, -m <MODEL>         使用的模型 (預設: deepseek-v3)
    --mode, -t <file|topic>     輸入模式 (預設: file)
    --verbose, -v               詳細輸出
    --help, -h                  顯示此幫助訊息

示例:
    bash $0 --input data/papers/sample.md
    bash $0 --input "IAQ monitoring" --mode topic
    bash $0 --input paper.pdf --output ./results --model llama-405b

EOF
}

check_dependencies() {
    log_info "檢查依賴..."
    
    # 檢查 Python
    if ! command -v python3 &> /dev/null; then
        log_error "Python 3 未安裝"
        exit 1
    fi
    
    # 檢查配置文件
    if [ ! -f "$CONFIG_FILE" ]; then
        log_warning "配置文件不存在: $CONFIG_FILE"
        log_info "使用預設配置..."
    fi
    
    log_success "依賴檢查完成"
}

create_output_dir() {
    if [ ! -d "$OUTPUT_DIR" ]; then
        mkdir -p "$OUTPUT_DIR"
        log_info "創建輸出目錄: $OUTPUT_DIR"
    fi
}

generate_timestamp() {
    date +"%Y%m%d_%H%M%S"
}

run_analysis() {
    local input_file="$1"
    local output_file="$OUTPUT_DIR/phd_analysis_$(generate_timestamp).md"
    
    log_info "開始 PhD Deep Analysis..."
    log_info "輸入: $input_file"
    log_info "輸出: $output_file"
    
    # 檢查輸入
    if [ ! -f "$input_file" ] && [ "$MODE" != "topic" ]; then
        log_error "輸入檔案不存在: $input_file"
        exit 1
    fi
    
    # 讀取 Prompt 模板
    local prompt_file="$ROOT_DIR/f-ros/phd_deep_mode/prompt.md"
    if [ ! -f "$prompt_file" ]; then
        log_error "Prompt 模板不存在: $prompt_file"
        exit 1
    fi
    
    local prompt_content
    prompt_content=$(cat "$prompt_file")
    
    # 生成分析內容
    local input_content=""
    if [ "$MODE" == "file" ]; then
        input_content=$(cat "$input_file")
    else
        input_content="$input_file"
    fi
    
    # 組合完整 Prompt
    local full_prompt="$prompt_content

---

## 任務輸入

$input_content

---

## 執行要求

請根據上述輸入，執行完整的 PhD Deep Analysis，產出：
1. 5個核心問題
2. 主題歸納（5-10個）
3. 矛盾分析
4. 研究缺口
5. 章節建議

## 輸出語言
繁體中文
"
    
    # 這裡是實際調用 AI API 的邏輯
    # 目前使用占位符，實際需要根據模型配置調用
    
    cat > "$output_file" << EOF
# PhD Deep Analysis Report

## 基本資訊

- **分析時間**: $(date "+%Y-%m-%d %H:%M:%S")
- **輸入模式**: $MODE
- **使用模型**: $MODEL
- **輸入來源**: $input_file

---

$full_prompt

---

## 使用說明

此為模板輸出。實際使用時，請將此檔案與 Fang Research OS 的 AI 分析引擎結合。

## 下一步

1. 將此檔案與 OpenClaw 整合
2. 使用正確的 API Key 配置
3. 執行實際的 AI 分析

---

*Generated by Fang Research OS v1.0*
*URL: https://github.com/ssiweifnag/Fang-Research-OS*
EOF

    log_success "分析完成！輸出檔案: $output_file"
    
    # 顯示結果（如果 verbose）
    if [ "$VERBOSE" = true ]; then
        echo ""
        echo "--- 輸出預覽 ---"
        head -50 "$output_file"
    fi
}

#----------------------------------------------------------------------------
# 主程式
#----------------------------------------------------------------------------

main() {
    # 解析參數
    while [[ $# -gt 0 ]]; do
        case $1 in
            --input|-i)
                INPUT="$2"
                shift 2
                ;;
            --output|-o)
                OUTPUT_DIR="$2"
                shift 2
                ;;
            --model|-m)
                MODEL="$2"
                shift 2
                ;;
            --mode|-t)
                MODE="$2"
                shift 2
                ;;
            --verbose|-v)
                VERBOSE=true
                shift
                ;;
            --help|-h)
                HELP=true
                shift
                ;;
            *)
                log_error "未知參數: $1"
                show_help
                exit 1
                ;;
        esac
    done
    
    # 顯示幫助
    if [ "$HELP" = true ]; then
        show_help
        exit 0
    fi
    
    # 檢查必填參數
    if [ -z "$INPUT" ]; then
        log_error "缺少必填參數: --input"
        show_help
        exit 1
    fi
    
    # 執行流程
    log_info "========================================"
    log_info "  Fang Research OS v1.0 - PhD Deep Analysis"
    log_info "========================================"
    echo ""
    
    check_dependencies
    create_output_dir
    run_analysis "$INPUT"
    
    echo ""
    log_success "PhD Deep Analysis 完成！"
    log_info "輸出檔案位於: $OUTPUT_DIR"
}

#----------------------------------------------------------------------------
# 執行
#----------------------------------------------------------------------------

main "$@"
