#!/bin/bash
#=============================================================================
# Fang Research OS v1.0 - Reviewer Killer Script
# 期刊防禦腳本
# 
# 用法:
#   bash scripts/reviewer_killer.sh --paper <FILE> [--output <DIR>]
#
# 示例:
#   bash scripts/reviewer_killer.sh --paper data/papers/sample.md
#=============================================================================

set -euo pipefail

# 顏色定義
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# 配置
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$ROOT_DIR/config/f-ros.yaml"

# 預設值
PAPER=""
OUTPUT_DIR="$ROOT_DIR/outputs"
MODEL="llama-405b"
VERBOSE=false
HELP=false

#----------------------------------------------------------------------------
# 函數
#----------------------------------------------------------------------------

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

show_help() {
    cat << EOF
Fang Research OS v1.0 - Reviewer Killer Script

用法:
    bash $0 [OPTIONS]

選項:
    --paper, -p <FILE>    論文檔案 (必填)
    --output, -o <DIR>   輸出目錄 (預設: ./outputs)
    --model, -m <MODEL>  使用的模型 (預設: llama-405b)
    --verbose, -v        詳細輸出
    --help, -h           顯示幫助

示例:
    bash $0 --paper data/papers/sample.md
    bash $0 --paper paper.pdf --output ./results

EOF
}

check_dependencies() {
    log_info "檢查依賴..."
    if ! command -v python3 &> /dev/null; then
        log_error "Python 3 未安裝"
        exit 1
    fi
    log_success "依賴檢查完成"
}

create_output_dir() {
    if [ ! -d "$OUTPUT_DIR" ]; then
        mkdir -p "$OUTPUT_DIR"
        log_info "創建輸出目錄: $OUTPUT_DIR"
    fi
}

generate_timestamp() {
    date +"%Y%m%d_%H%M%S"
}

run_defense_analysis() {
    local paper_file="$1"
    local output_file="$OUTPUT_DIR/reviewer_defense_$(generate_timestamp).md"
    
    log_info "開始 Reviewer Killer Analysis..."
    log_info "論文: $paper_file"
    
    # 檢查論文檔案
    if [ ! -f "$paper_file" ]; then
        log_error "論文檔案不存在: $paper_file"
        exit 1
    fi
    
    # 讀取 Prompt
    local prompt_file="$ROOT_DIR/f-ros/reviewer_killer/prompt.md"
    if [ ! -f "$prompt_file" ]; then
        log_error "Prompt 模板不存在: $prompt_file"
        exit 1
    fi
    
    local prompt_content
    prompt_content=$(cat "$prompt_file")
    
    local paper_content
    paper_content=$(cat "$paper_file")
    
    # 生成完整 Prompt
    local full_prompt="$prompt_content

---

## 論文內容

$paper_content

---

## 執行要求

請針對上述論文，執行完整的 Reviewer Killer Analysis：

1. 【主要發現】- 識別論文核心貢獻
2. 【方法優勢】- 找出方法論的強項
3. 【方法缺陷】- 找出潛在弱點
4. 【統計完整性檢查】- 評估統計方法
5. 【潛在審稿質疑點】- 預測審稿問題
6. 【如何預先防禦】- 提供補強方案

## 輸出語言
繁體中文

EOF
    
    # 生成輸出
    cat > "$output_file" << EOF
# Reviewer Killer Analysis Report

## 基本資訊

- **分析時間**: $(date "+%Y-%m-%d %H:%M:%S")
- **論文檔案**: $paper_file
- **使用模型**: $MODEL
- **輸出檔案**: $output_file

---

## 審稿預防分析

### 1. 主要發現

[待 AI 分析填入]

### 2. 方法優勢

[待 AI 分析填入]

### 3. 方法缺陷

[待 AI 分析填入]

### 4. 統計完整性檢查

| 項目 | 評估 | 建議 |
|------|------|------|
| 樣本數 | 待評估 | |
| 顯著性 | 待評估 | |
| 效度 | 待評估 | |

### 5. 潛在審稿質疑點

| 質疑點 | 可能性 | 嚴重程度 |
|--------|--------|----------|
| [質疑1] | 高/中/低 | 高/中/低 |
| [質疑2] | 高/中/低 | 高/中/低 |

### 6. 如何預先防禦

#### 防禦策略1
[策略內容]

#### 防禦策略2
[策略內容]

---

## 使用說明

此為模板輸出。實際使用時，請配置正確的 API Key。

## 下一步

1. 配置 AI API Key
2. 執行實際分析
3. 根據建議修改論文

---

*Generated by Fang Research OS v1.0*
*URL: https://github.com/ssiweifnag/Fang-Research-OS*
EOF

    log_success "分析完成！輸出檔案: $output_file"
    
    if [ "$VERBOSE" = true ]; then
        echo ""
        echo "--- 輸出預覽 ---"
        head -30 "$output_file"
    fi
}

main() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --paper|-p) PAPER="$2"; shift 2 ;;
            --output|-o) OUTPUT_DIR="$2"; shift 2 ;;
            --model|-m) MODEL="$2"; shift 2 ;;
            --verbose|-v) VERBOSE=true; shift ;;
            --help|-h) show_help; exit 0 ;;
            *) log_error "未知參數: $1"; show_help; exit 1 ;;
        esac
    done
    
    if [ -z "$PAPER" ]; then
        log_error "缺少必填參數: --paper"
        show_help
        exit 1
    fi
    
    log_info "========================================"
    log_info "  Fang Research OS v1.0 - Reviewer Killer"
    log_info "========================================"
    echo ""
    
    check_dependencies
    create_output_dir
    run_defense_analysis "$PAPER"
    
    echo ""
    log_success "Reviewer Killer Analysis 完成！"
}

main "$@"
