#!/bin/bash
#=============================================================================
# Fang Research OS v1.0 - SCI Agent Script
# SCI 智能體腳本
# 
# 用法:
#   bash scripts/sci_agent.sh --topic <TOPIC> [--output <DIR>] [--mode <MODE>]
#
# 示例:
#   bash scripts/sci_agent.sh --topic "IAQ mmWave carbon"
#   bash scripts/sci_agent.sh --topic "智慧建築節能" --mode comprehensive
#=============================================================================

set -euo pipefail

# 顏色定義
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# 配置
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
CONFIG_FILE="$ROOT_DIR/config/f-ros.yaml"

# 預設值
TOPIC=""
OUTPUT_DIR="$ROOT_DIR/outputs"
MODEL="deepseek-v3"
MODE="comprehensive"
VERBOSE=false
HELP=false

#----------------------------------------------------------------------------
# 函數
#----------------------------------------------------------------------------

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_debug() { if [ "$VERBOSE" = true ]; then echo -e "${CYAN}[DEBUG]${NC} $1"; fi; }

show_help() {
    cat << EOF
Fang Research OS v1.0 - SCI Agent Script

用法:
    bash $0 [OPTIONS]

選項:
    --topic, -t <TOPIC>   研究主題 (必填)
    --output, -o <DIR>    輸出目錄 (預設: ./outputs)
    --model, -m <MODEL>  使用的模型 (預設: deepseek-v3)
    --mode, -M <MODE>     分析模式 (basic/comprehensive/deep)
    --verbose, -v         詳細輸出
    --help, -h            顯示幫助

示例:
    bash $0 --topic "IAQ monitoring mmWave"
    bash $0 --topic "智慧建築節能" --mode comprehensive
    bash $0 --topic "carbon accounting" --output ./results --model llama-405b

分析模式:
    basic       - 基礎分析 (3 步驟)
    comprehensive - 完整分析 (8 步驟) [預設]
    deep        - 深度分析 (含更多細節)

EOF
}

check_dependencies() {
    log_info "檢查依賴..."
    
    if ! command -v python3 &> /dev/null; then
        log_error "Python 3 未安裝"
        exit 1
    fi
    
    if [ ! -f "$CONFIG_FILE" ]; then
        log_warning "配置文件不存在: $CONFIG_FILE"
    fi
    
    log_success "依賴檢查完成"
}

create_output_dir() {
    if [ ! -d "$OUTPUT_DIR" ]; then
        mkdir -p "$OUTPUT_DIR"
        log_info "創建輸出目錄: $OUTPUT_DIR"
    fi
}

generate_timestamp() {
    date +"%Y%m%d_%H%M%S"
}

get_mode_steps() {
    local mode="$1"
    case "$mode" in
        basic)
            echo "1,2,4,5"
            ;;
        comprehensive)
            echo "1,2,3,4,5,6,7,8"
            ;;
        deep)
            echo "1,2,3,4,5,6,7,8"
            ;;
        *)
            echo "1,2,3,4,5,6,7,8"
            ;;
    esac
}

run_sci_analysis() {
    local topic="$1"
    local output_file="$OUTPUT_DIR/sci_agent_$(generate_timestamp).md"
    local steps=$(get_mode_steps "$MODE")
    
    log_info "開始 SCI Agent Analysis..."
    log_info "主題: $topic"
    log_info "模式: $MODE"
    log_info "步驟: $steps"
    
    # 讀取 Prompt
    local prompt_file="$ROOT_DIR/f-ros/sci_agent/prompt.md"
    if [ ! -f "$prompt_file" ]; then
        log_error "Prompt 模板不存在: $prompt_file"
        exit 1
    fi
    
    local prompt_content
    prompt_content=$(cat "$prompt_file")
    
    # 生成完整 Prompt
    local full_prompt="$prompt_content

---

## 研究主題

$topic

---

## 分析模式

模式: $MODE
步驟: $steps

## 執行要求

請針對上述主題，執行 SCI Agent Ultimate Analysis。

### 分析步驟

1. 生成5個核心研究問題
2. 識別主流理論與實證立場
3. 找出關鍵矛盾與衝突證據
4. 識別未解決研究缺口
5. 評估方法學嚴謹度
6. 提出可發表等級研究改進建議
7. [擴展] 模擬審稿攻擊
8. [擴展] 創新潛力評估

## 輸出結構

I. 概覽（研究意義與背景）
II. 證據支持之主張
III. 方法學批判
IV. 矛盾與限制
V. 可發展新研究方向
VI. 信心水平評估（高/中/低）

## 輸出語言
繁體中文

EOF
    
    # 生成輸出
    cat > "$output_file" << EOF
# SCI Agent Analysis Report

## 基本資訊

- **分析時間**: $(date "+%Y-%m-%d %H:%M:%S")
- **研究主題**: $topic
- **分析模式**: $MODE
- **執行步驟**: $steps
- **使用模型**: $MODEL
- **輸出檔案**: $output_file

---

## 分析結果

### I. 概覽

**研究意義與背景**

[待 AI 分析填入]

**核心貢獻**

[待 AI 分析填入]

---

### II. 證據支持之主張

**主要發現**

[待 AI 分析填入]

**支持證據**

[待 AI 分析填入]

**信心水平評估**

| 維度 | 信心水平 | 說明 |
|------|----------|------|
| 主要發現 | 高/中/低 | |
| 證據強度 | 高/中/低 | |
| 結論可靠性 | 高/中/低 | |

---

### III. 方法學批判

**優勢**

[待 AI 分析填入]

**局限**

[待 AI 分析填入]

**改進建議**

[待 AI 分析填入]

---

### IV. 矛盾與限制

**內部矛盾**

[待 AI 分析填入]

**外部限制**

[待 AI 分析填入]

**未解決爭議**

[待 AI 分析填入]

---

### V. 可發展新研究方向

**短期可行方向**

[待 AI 分析填入]

**長期研究方向**

[待 AI 分析填入]

**跨領域機會**

[待 AI 分析填入]

---

### VI. 審稿預防

**預期審稿問題**

[待 AI 分析填入]

**防禦策略**

[待 AI 分析填入]

---

## 下一步行動

- [ ] 根據分析結果調整研究方向
- [ ] 補強方法論弱點
- [ ] 擴展文獻閱讀
- [ ] 準備期刊投稿

---

*Generated by Fang Research OS v1.0*
*URL: https://github.com/ssiweifnag/Fang-Research-OS*
*分析模式: $MODE*
EOF

    log_success "SCI Agent Analysis 完成！"
    log_info "輸出檔案: $output_file"
    
    if [ "$VERBOSE" = true ]; then
        echo ""
        echo "--- 輸出預覽 ---"
        head -40 "$output_file"
    fi
}

main() {
    while [[ $# -gt 0 ]]; do
        case $1 in
            --topic|-t) TOPIC="$2"; shift 2 ;;
            --output|-o) OUTPUT_DIR="$2"; shift 2 ;;
            --model|-m) MODEL="$2"; shift 2 ;;
            --mode|-M) MODE="$2"; shift 2 ;;
            --verbose|-v) VERBOSE=true; shift ;;
            --help|-h) show_help; exit 0 ;;
            *) log_error "未知參數: $1"; show_help; exit 1 ;;
        esac
    done
    
    if [ -z "$TOPIC" ]; then
        log_error "缺少必填參數: --topic"
        show_help
        exit 1
    fi
    
    log_info "========================================"
    log_info "  Fang Research OS v1.0 - SCI Agent"
    log_info "========================================"
    echo ""
    
    check_dependencies
    create_output_dir
    run_sci_analysis "$TOPIC"
    
    echo ""
    log_success "SCI Agent Analysis 完成！"
}

main "$@"
